config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :albums, :wishlist_albums

  get 'welcome/index'
  get '/search' => 'albums#search', :as => 'search_page'
  get 'albums/:id/move' => 'albums#move', :as => 'move_album'
  get '/help' => 'welcome#help', :as => 'help_page'

  post 'albums/new' => 'albums#new', :as => 'new_album_page'
  post 'wishlist_albums/new' => 'wishlist_albums#new', :as => 'new_wishlist_album_page'
  post 'albums/:id/move' => 'albums#move', :as => 'move_album_page'

  root 'welcome#index'

end

app/models/album.rb
class Album < ApplicationRecord
    belongs_to :user
    has_one_attached :album_image
    # after_create :set_filename
    
    validates :artist, presence: true,
                length: {minimum: 1}
    validates :album_title, presence: true,
                length: {minimum: 1}
    validates :year_released, 
                length: {minimum: 4, maximum: 4}

  #   def set_filename
  #     if self.active_storage_object.attached?
  #       self.active_storage_object.blob.update(filename: "desired_filename.#{self.active_storage_object.filename.extension}")
  #   end
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :albums
  has_many :wishlist_albums
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/wishlist_album.rb
class WishlistAlbum < ApplicationRecord
    belongs_to :user
    
    validates :artist, presence: true,
                length: {minimum: 1}
    validates :album_title, presence: true,
                length: {minimum: 1}
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  helper_method :sort_column, :sort_direction

    def index
      @albums = current_user.albums.order(sort_column + " " + sort_direction)
    end

    def show
      @album = Album.find(params[:id])
    end

    def new
      @album = current_user.albums.new
    end

    def edit
      @album = Album.find(params[:id])
    end

    def create
      @album = Album.new(album_params.merge(user_id: current_user.id))
 
      if @album.save
        redirect_to @album
      else 
        render 'new'
      end
    end

    def update
      @album = Album.find(params[:id])
       
      if @album.update(album_params)
        redirect_to @album
      else
        render 'edit'
      end
    end

    def destroy
      @album = Album.find(params[:id])
      @album.destroy
       
      redirect_to albums_path
    end

    def search
      if params[:search].blank?  
        flash[:alert] = "Error: Please enter an artist!"
        redirect_to :albums
      else 
        album_params = params[:search].downcase  
        @albums = current_user.albums.all.where("lower(artist) LIKE :search", search: album_params)
      end  
    end

    def move
      @album = WishlistAlbum.find(params[:id])
      @album = Album.new(wishlist_album_params)

      @wishlist_album = WishlistAlbum.find(params[:id])
      @wishlist_album.destroy
    end

    private
      def album_params
        params.require(:album).permit(:artist, :album_title, :year_released, :genre, :grade, :notes, :album_image)
      end

      def wishlist_album_params
        params.permit(:wishlist_album).permit(:artist, :album_title)
      end
  
      def sort_column
        Album.column_names.include?(params[:sort]) ? params[:sort] : "artist"
      end
  
      def sort_direction
        %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
      end
    end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!

private
  def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wishlist_albums_controller.rb
class WishlistAlbumsController < ApplicationController
  helper_method :sort_column, :sort_direction

    def index
      @wishlist_albums = current_user.wishlist_albums.order(sort_column + " " + sort_direction)
    end

    def show
      @wishlist_album = WishlistAlbum.find(params[:id])
    end

    def new
      @wishlist_album = current_user.wishlist_albums.new
    end

    def edit
      @wishlist_album = WishlistAlbum.find(params[:id])
    end

    def create
      @wishlist_album = WishlistAlbum.new(wishlist_album_params.merge(user_id: current_user.id))
       
        if @wishlist_album.save
          redirect_to action: 'index'
        else
          render 'new'
        end
    end

    def update
      @wishlist_album = WishlistAlbum.find(params[:id])

      if @wishlist_album.update(wishlist_album_params)
        redirect_to @wishlist_album
      else
        render 'edit'
      end
    end

    def destroy
      @wishlist_album = WishlistAlbum.find(params[:id])
      @wishlist_album.destroy

      redirect_to wishlist_albums_path
    end

    def move
    end

    private
    def wishlist_album_params
      params.require(:wishlist_album).permit(:artist, :album_title)
    end

    def sort_column
      WishlistAlbum.column_names.include?(params[:sort]) ? params[:sort] : "artist"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    
  def sortable(column, title = nil)
    title ||= column.titleize
    album_col_link = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => album_col_link}
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wishlist_albums_helper.rb
module WishlistAlbumsHelper
end

app/views/albums/_form.html.erb
<div class="row">
  <div class="col-md-5">
    <%= bootstrap_form_with(model: @album, local: true) do |form| %>

    <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2>
        <h3>WARNING!</h3>
        <%= pluralize(@album.errors.count, "error") %> prohibited
        this album from being saved:
      </h2>
      <ul>
        <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <br>
    <%= form.text_field :artist %>
    <%= form.text_field :album_title %>
    <%= form.text_field :year_released %>
    <%= form.text_field :genre %>
    <%= form.select :grade, ['', 'Poor (P) or Fair (F)', 'Good (G)', 'Very Good (VG)',
                      'Very Good Plus (VG+)', 'Excellent (E)', 'Near Mint (NM)', 'Mint (M)'] %>
    <%= form.text_area :notes %>
    <%= form.file_field :album_image %>

    <div class="pad-bottom-20">
      <%= form.submit class: "btn btn-outline-primary primary-font" %> <%= link_to 'Back to collection', albums_path, class: "btn btn-outline-primary primary-font" %>
    </div>

    <% end %>
  </div>
</div>

app/views/albums/edit.html.erb
<%= render "layouts/menu" %>

<div class="container">
    <br>
    <h1 class="primary-font">Edit Album</h1>

    <%= render 'form' %>

</div>

app/views/albums/index.html.erb
<%= render "layouts/menu" %>

<h1 class="jumbotron primary-font">Record Collection</h1>

<div class="container pad-bottom-20">
  <div class="row">
    <div class="col-md-6" id="album_search_bar">
      <% flash[:alert] %>

      <%= form_tag(search_page_path, method: :get) do %>
      <%= search_field_tag :search, params[:search], placeholder: "Search by artist" %>
      <%= button_tag 'Search', :name => nil, class: "btn btn-outline-primary search-btn primary-font" %>
      <% end %>
    </div>
    <div class="col-md-6 text-right">
      <%= button_to 'Add new album', new_album_path, class: "btn btn-outline-primary primary-font" %>
    </div>
  </div>
</div>

<div class="container">
  <div class="table-responsive-md">
    <table class="table table-hover">
      <thead class="thead-light">
        <tr class="album-table-link">
          <th scope="col"><%= sortable "artist" %></th>
          <th scope="col"><%= sortable "album_title" %></th>
          <th scope="col"><%= sortable "year_released" %></th>
          <th scope="col"><%= sortable "genre" %></th>
          <th scope="col" colspan="2" class="text-center">Actions</th>
        </tr>
      </thead>

      <% @albums.each do |album| %>
      <tr>
        <td><%= album.artist %></td>
        <td><%= link_to album.album_title, album_path(album), class: "album-table-link" %></td>
        <td><%= album.year_released %></td>
        <td><%= album.genre %></td>
        <td class="text-right"><%= link_to 'Edit', edit_album_path(album), class: "album-table-link" %></td>
        <td class="text-center"><%= link_to 'Delete', album_path(album), class: "album-table-link",
        method: :delete,
        data: { confirm: 'Are you sure you want to remove '+ album.album_title + ' from your collection?'} %></td>
      </tr>
      <% end %>
    </table>
    <div class="container">
      <div class="row pad-bottom-20">
        <%= link_to 'Back to home', welcome_index_path, class: "btn btn-outline-primary primary-font" %>
      </div>
    </div>
  </div>
</div>

app/views/albums/move.html.erb
<%= render "layouts/menu" %>

<div class="container">
  <br>
  <h1 class="primary-font">Move Album to Collection</h1>

  <div class="row">
    <div class="col-sm-4">
      <%= bootstrap_form_with(model: @album, local: true) do |form| %>

      <% if @album.errors.any? %>
      <div id="error_explanation">
        <h2>
          <h3>WARNING!</h3>
          <%= pluralize(@album.errors.count, "error") %> prohibited
          this album from being saved:
        </h2>
        <ul>
          <% @album.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <br>
      <%= form.text_field :artist %>
      <%= form.text_field :album_title %>
      <%= form.text_field :year_released %>
      <%= form.text_field :genre %>
      <%= form.select :grade, ['', 'Poor (P) or Fair (F)', 'Good (G)', 'Very Good (VG)',
                        'Very Good Plus (VG+)', 'Excellent (E)', 'Near Mint (NM)', 'Mint (M)'] %>
      <%= form.text_area :notes %>

      <div style="padding-bottom: 20px">
        <%= form.submit class: "btn btn-outline-primary primary-font" %>
      </div>

      <% end %>
    </div>
  </div>
</div>

app/views/albums/new.html.erb
<%= render "layouts/menu" %>

<div class="container">
    <br>
    <h1 class="primary-font">New album</h1>

    <%= render 'form' %>

</div>

app/views/albums/search.html.erb
<%= render 'layouts/menu' %>

<div class="container">
    <div class="row">
        <div class="col-md">
            <br>
            <h1 class="primary-font">Search Results</h1>
            <br>

            <% @albums.each do |album| %>

            <%= album.artist %> - <%= link_to album.album_title, album_path(album) %><br>

            <% end %>

            <% if @albums.blank? %>
            <div class="notice" style="color:Tomato;">Artist not found in your collection</div>
            <% end %>

            <br>
            <%= link_to 'Back to collection', albums_path, class: "btn btn-outline-primary" %>
        </div>
    </div>
</div>

app/views/albums/show.html.erb
<%= render "layouts/menu" %>

<h2 class="jumbotron text-center primary-font"><%= @album.artist %><br><%= @album.album_title %></h3>
  <div class="container text-center">
    <div class="col-md">

      <% if @album.album_image.blank? %>
      <p></p>
      <% else %>
      <p>
        <%= image_tag @album.album_image, style: 'height:300px;width:300px;' %>
      </p>
      <% end %>

      <p>
        <strong>Year released:</strong>
        <%= @album.year_released %>
      </p>

      <p>
        <strong>Genre:</strong>
        <%= @album.genre %>
      </p>

      <p>
        <strong>Grade:</strong>
        <%= @album.grade %>
      </p>

      <p>
        <strong>Notes:</strong>
        <%= @album.notes %>
      </p>

      <%= link_to 'Edit album', edit_album_path(@album), class: "btn btn-outline-primary primary-font" %>
      <%= link_to 'Back to collection', albums_path, class: "btn btn-outline-primary primary-font" %>
      <br>
      <br>
    </div>
  </div>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-md navbar-dark">
    <% if user_signed_in? %>
    <%= link_to 'My Record Collection', welcome_index_path, :class => 'navbar-header primary-font navbar-brand', :style => "color:whitesmoke; font-size: 20px" %>

    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
        <ul class="navbar-nav justify-content-end">
            <li class="nav-item">
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link', :style => "color:whitesmoke; padding-left: 10px;" %>
            </li>
            <li class="nav-item">
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link', :style => "color:whitesmoke; padding-left: 10px;"  %>
            </li>
            <% else %>
            <li class="nav-item">
                <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link', :style => "color:whitesmoke"  %>
            </li>
            <li class="nav-item">
                <%= link_to "Login", new_user_session_path, :class => 'nav-link', :style => "color:whitesmoke"  %>
            </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/_menu_home.html.erb
<nav class="navbar navbar-expand-md navbar-dark">
    <div class="navbar-header primary-font navbar-brand">
        <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>
    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
        <ul class="navbar-nav">
            <li class="nav-item">
                <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link', :style => "color:whitesmoke; padding-left: 10px;" %>
            </li>
            <li class="nav-item">
                <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link', :style => "color:whitesmoke; padding-left: 10px;"  %>
            </li>
            <% else %>
            <li class="nav-item">
                <%= link_to "Sign up", new_user_registration_path, :class => 'nav-link', :style => "color:whitesmoke"  %>
            </li>
            <li class="nav-item">
                <%= link_to "Login", new_user_session_path, :class => 'nav-link', :style => "color:whitesmoke"  %>
            </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>My Record Collection</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src='https://kit.fontawesome.com/a076d05399.js'></script>
</head>

<body>
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <%= yield %>
</body>

</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Login", new_session_path(resource_name), class: "btn btn-outline-primary primary-font" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-outline-primary primary-font" %><br />
<% end %>

<!-- <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %> -->

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/welcome/help.html.erb
<%= render "layouts/menu" %>

<h1 class="jumbotron primary-font">Learn How to Use</h1>

<div class="container" style="width: 60%;">

    <div class="text-center">
        <h3>Getting Started</h3>

        <p>My Record Collection is designed to be simple to understand and easy to use. This app provides
            a clean user-interface to make archiving your vinyl record collection a peice of cake. To get started,
            create an account by clicking the 'Sign up' link and enter your e-mail address and a secure password of
            at least six characters. From there, click on the 'My Collection' button under the record icon on the
            main Welcome page.
        <p>

        <h3>Start Adding Albums to Your Collection</h3>

        <p>Adding albums is easy, click the 'Add new album' button and start entering information about the
            album on the form. Artist, album title, year released and genre are required fields, meaning the
            album will not be added to your collection without providing this information. Album grade and notes
            are optional fields; learn more about how to grade your albums
            <%= link_to 'here', "https://blog.electrohome.com/vinyl-grading-system-shop-used-records/", :target => "_blank" %>.
            Click the 'Create Album' button to save it and you will then see the album in your collection!
        </p>

        <h3>Add Albums You Want to Your Wish List</h3>

        <p>Wish list albums are albums you do not own but are looking to add to your collection.
            Adding wish list albums is essentially the same process as adding albums, the only difference is it only
            has two fields and they are both required: artist and album title. The main feature of wish list albums
            is they can easily be moved over to your collection. Click the 'Move to collection' link and a popup will
            appear explaining how the process works. Once you click 'Ok' the album will be removed from your wish list
            and you will have to re-enter the information along with the other required fields for an album and you're
            done, simple as that.
        </p>
    </div>


</div>


<div class="container" style="padding-top: 20px;">
    <%= link_to 'Back to Home', welcome_index_path, class: "btn btn-outline-primary primary-font" %>
</div>
<br>

app/views/welcome/index.html.erb
<%= render "layouts/menu_home" %>

<h1 class="jumbotron text-center primary-font">Welcome to My Record Collection</h1>
<div class="container text-center">
    <div class="row" style="padding-top: 40px;">
        <div class="col-4">
            <i class='fas fa-compact-disc' style='font-size:64px; color:rgb(76, 90, 104); padding-bottom: 10px'></i>
            <div>
                <%= link_to 'My Collection', albums_path, class: "btn btn-outline-primary primary-font" %>
            </div>
        </div>
        <div class="col-4">
            <i class='fas fa-gifts' style='font-size:64px; color:rgb(76, 90, 104); padding-bottom: 10px'></i>
            <div>
                <%= link_to 'My Wish List', wishlist_albums_path, class: "btn btn-outline-primary primary-font" %>
            </div>
        </div>
        <div class="col-4">
            <i class='far fa-question-circle' style='font-size:64px; color:rgb(76, 90, 104); padding-bottom: 10px'></i>
            <div>
                <%= link_to 'Get Help Here', help_page_path, class: "btn btn-outline-primary primary-font" %>
            </div>
        </div>
    </div>
</div>

app/views/wishlist_albums/_form.html.erb
<div class="row">
    <div class="col-md-5">
        <%= bootstrap_form_with(model: @wishlist_album, local: true) do |form| %>

        <% if @wishlist_album.errors.any? %>
        <div id="error_explanation">
            <h2>
                <h3>WARNING!</h3>
                <%= pluralize(@wishlist_album.errors.count, "error") %> prohibited
                this album from being saved:
            </h2>
            <ul>
                <% @wishlist_album.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
        <% end %>

        <br>
        <%= form.text_field :artist %>
        <%= form.text_field :album_title %>

        <%= form.submit class: "btn btn-outline-primary primary-font" %>
        <%= link_to 'Back to wish list', wishlist_albums_path, class: "btn btn-outline-primary primary-font" %>
        </br>
        </br>

        <% end %>
    </div>
</div>

app/views/wishlist_albums/edit.html.erb
<%= render 'layouts/menu' %>

<div class="container">
  <br>
  <h1 class="primary-font">Edit wish list album</h1>

  <%= render 'form' %>

</div>

app/views/wishlist_albums/index.html.erb
<%= render "layouts/menu" %>

<h1 class="jumbotron primary-font">Wish List Albums</h1>

<div class="container">
  <div class="row pad-bottom-20">
    <div class="col-md text-right">
      <%= button_to 'New wish list album', new_wishlist_album_path, class: "btn btn-outline-primary primary-font" %>
    </div>
  </div>
</div>

<div class="container">
  <div class="table-responsive-md">
    <table class="table table-md table-hover">
      <thead class="thead-light">
        <tr>
          <th scope="col"><%= sortable 'artist' %></th>
          <th scope="col"><%= sortable 'album_title' %></th>
          <th scope="col" colspan="3" class="text-center width-25">Actions</th>
        </tr>
      </thead>

      <% @wishlist_albums.each do |wishlist_album| %>
      <tr>
        <td><%= wishlist_album.artist %></td>
        <td><%= wishlist_album.album_title %></td>
        <td class="text-right">
          <%= link_to 'Edit', edit_wishlist_album_path(wishlist_album), class: "album-table-link" %></td>
        <td class="text-right"><%= link_to 'Move to collection', move_album_path(wishlist_album), class: "album-table-link",
              method: :move,
              data: {confirm: "Move "+ wishlist_album.album_title + " to collection?\n\n" +
            "Note: This will remove the album from your wish list and the album \ndetails will need to be " +
          "re-entered on the following form."} %></td>
        <td class="text-right">
          <%= link_to 'Delete', wishlist_album_path(wishlist_album), class: "album-table-link",
              method: :delete,
              data: { confirm: 'Are you sure you want to remove '+ wishlist_album.album_title + ' from your wishlist?' } %>
        </td>
      </tr>
      <% end %>
    </table>
    <div class="container">
      <div class="row pad-bottom-20">
        <%= link_to 'Back to home', welcome_index_path, class: "btn btn-outline-primary primary-font" %>
      </div>
    </div>
  </div>
</div>

app/views/wishlist_albums/new.html.erb
<%= render 'layouts/menu' %>

<div class="container">
  <br>
  <h1 class="primary-font">Add wish list album</h1>

  <%= render 'form' %>

</div>

app/views/wishlist_albums/show.html.erb
<%= render 'layouts/menu' %>

<p>
    <strong>Artist:</strong>
    <%= @wishlist_album.artist %>
</p>

<p>
    <strong>Album title:</strong>
    <%= @wishlist_album.album_title %>
</p>

<%= link_to 'Back to wishlist', wishlist_albums_path %>